!write down the list of aspic models sorted according to the number of
!potential parameters and if the end of inflation is a model parameter
!or not. XEND means it is an extra param, as opposed to PURE.

ZEROPP_PURE(hi)

ONEPP_PURE(rchi)
ONEPP_PURE(lfi)
ONEPP_PURE(rcmi)
ONEPP_PURE(rcqi)
ONEPP_PURE(ni)
ONEPP_PURE(esi)
ONEPP_PURE(pli)
ONEPP_PURE(kmii)
ONEPP_PURE(hf1i)
ONEPP_PURE(li)
ONEPP_PURE(rpi1)
ONEPP_PURE(dwi)
ONEPP_PURE(mhi)
ONEPP_PURE(rgi)
ONEPP_PURE(mssmi)
ONEPP_PURE(ripi)
ONEPP_PURE(ai)
ONEPP_PURE(cnai)
ONEPP_PURE(cnbi)
ONEPP_PURE(osti)
ONEPP_PURE(wri)

ONEPP_XEND(rpi2)
ONEPP_XEND(ii)
ONEPP_XEND(twi)
ONEPP_XEND(bsusybi)
ONEPP_XEND(csi)
ONEPP_XEND(cnci)
ONEPP_XEND(imi)

TWOPP_PURE(cwi)
TWOPP_PURE(sfi)
TWOPP_PURE(kmiii)
TWOPP_PURE(lmi1)
TWOPP_PURE(gmssmi)
TWOPP_PURE(gripi)
TWOPP_PURE(ti)
TWOPP_PURE(bei)
TWOPP_PURE(psni)
TWOPP_PURE(ncki)
TWOPP_PURE(oi)
TWOPP_PURE(sbi)
TWOPP_PURE(ssbi1)
TWOPP_PURE(ssbi2)
TWOPP_PURE(ssbi3)
TWOPP_PURE(ssbi4)
TWOPP_PURE(ssbi5)
TWOPP_PURE(ssbi6)

TWOPP_XEND(lmi2)
TWOPP_XEND(rmi1)
TWOPP_XEND(rmi2)
TWOPP_XEND(rmi3)
TWOPP_XEND(rmi4)
TWOPP_XEND(vhi)
TWOPP_XEND(dsi)
TWOPP_XEND(cndi)

TWOPP_XEND_XINI(bi)
TWOPP_XEND_XINI(kklti)

THREEPP_PURE(gmlfi)
THREEPP_PURE(lpi1)
THREEPP_PURE(lpi2)
THREEPP_PURE(lpi3)
